### ISSUE TITLE
ValueError when running run_load_muse.sh

### ISSUE THREAD

**Issue by AiHubCN** [thespectrewithin/cross-lingual_NER#2]
Hi,
When I run the script run_load_muse.sh, there is a ValueError:

Traceback (most recent call last):
  File "load_muse.py", line 118, in <module>
    main()
  File "load_muse.py", line 100, in main
    eng_word, eng_vec, engs = load_embedding(args.eng_path, args.vocab_size)
  File "load_muse.py", line 78, in load_embedding
    return word_dict, normalize(np.vstack(word_vector)), words
  File "/home/data/v-huawu/anaconda3/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

 Could do you know how to solve it? 

I have deleted the 1st line that specifies the size and the dimension of the embedding file, and I use the word embedding file from https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.en.vec

**Comment by thespectrewithin** [comment]
Fixed. There's a weird character in the word embedding file that Python 3.6 handles differently. Didn't notice previously.

**Comment by thespectrewithin** [comment]
fixed. let me know if there are any more issues. Thanks

**Comment by AiHubCN** [comment]
Thank you very much!
