### ISSUE TITLE
issues when running run_lasagne_ncrf.sh

### ISSUE THREAD

**Issue by AiHubCN** [thespectrewithin/cross-lingual_NER#4]
Hi~

There are some issues when I run the run_lasagne_ncrf.sh:

 ** On entry to SGEMM  parameter number 15 had an illegal value
Traceback (most recent call last):
  File "/home/***/software/Theano/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: cublasHgemmStridedBatched: (cublas) Invalid value.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lasagne_ncrf.py", line 354, in <module>
    main()
  File "lasagne_ncrf.py", line 299, in main
    batchloss, corr, num = train(char_input, char_input_mask, word_input, word_input_mask, label_input)
  File "/home/***/software/Theano/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/***/software/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/***/anaconda3/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/***/software/Theano/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: cublasHgemmStridedBatched: (cublas) Invalid value.
Apply node that caused the error: GpuGemmBatch{inplace=True}(InplaceGpuDimShuffle{0,2,1}.0, TensorConstant{1.0}, GpuElemwise{mul}[]<gpuarray>.0, GpuElemwise{mul,no_inplace}.0, TensorConstant{1.0})
Toposort index: 1608
Inputs types: [GpuArrayType<None>(float32, 3D), TensorType(float32, scalar), GpuArrayType<None>(float32, 3D), GpuArrayType<None>(float32, 3D), TensorType(float32, scalar)]
Inputs shapes: [(1, 10, 400), (), (1, 10, 10), (1, 10, 400), ()]
Inputs strides: [(4, 4, 40), (), (400, 40, 4), (16000, 1600, 4), ()]
Inputs values: ['not shown', array(1., dtype=float32), 'not shown', 'not shown', array(1., dtype=float32)]
Outputs clients: [[GpuElemwise{Composite{(i0 * i1 * (i2 - sqr(i3)))}}[(0, 3)]<gpuarray>(GpuGemmBatch{inplace=True}.0, InplaceGpuDimShuffle{0,1,x}.0, GpuArrayConstant{[[[1.]]]}, GpuElemwise{Composite{tanh((i0 + i1))}}[]<gpuarray>.0)]]

I have checked the data, it doesn't have any problem.

I am using Theano 1.0 and Lasagne 0.2.

Thank you!

**Comment by thespectrewithin** [comment]
What’s your cuda and cudnn version?

**Comment by AiHubCN** [comment]
My cuda version is 9.0 and cudnn version is cudnn-9.0-linux-x64-v7.

Thank you!

**Comment by AiHubCN** [comment]
The error is fixed by modifying the batch size to 32, it's quite strange!

**Comment by thespectrewithin** [comment]
It's pretty weird, but it may have sth to do with CUDA and CUDNN versions. I used a lower one for theano (cuda 8, cudnn 7, and there're no bugs when I run it).
