### ISSUE TITLE
run_pytorch_ncrf failed 

### ISSUE THREAD

**Issue by Jorigorn** [thespectrewithin/cross-lingual_NER#5]
Hi, thanks for open source the code, I am trying to reproduce the results,
Could you please help me have a look at this error?
I can run run_lasagne_ncrf.sh successfully, see the log below.  run_pytorch_ncrf failed, everything else is the same. Both update the vocab and dim size for the glove embedding.
I use another different glove word embedding.

% sh ./run_pytorch_ncrf.sh
$ CUDA_VISIBLE_DEVICES=0,1,2,3 python pytorch_ncrf.py --train_data ./conll2002/esp.train_transferred_fasttext_idc_withoutDOCS --dev_data ./conll2002/esp.testa_withoutDOCS --test_data ./conll2002/esp.testb_withoutDOCS --word_vec_path ./glove-sbwc.i25_withou_head_d_s.vec --seed 10 --word_dropout 0.5 --use_crf --self_att --att_dropout 0.5 --log_interval 150 --log_path ./esp_sa_fasttext_idc_result
loading data...
/home/john/anaconda3/envs/cross-lingual_NER/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/mnt/hdd/experiments/john/cross-lingual_NER/pytorch_crf.py:60: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(self.state_nn.bias, 0.)
/mnt/hdd/experiments/john/cross-lingual_NER/pytorch_crf.py:62: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(self.trans_nn.weight)
/mnt/hdd/experiments/john/cross-lingual_NER/pytorch_crf.py:63: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(self.trans_nn.bias, 0.)
training...
pytorch_ncrf.py:84: UserWarning: volatile was removed (Variable.volatile is always False)
  filler = Variable(torch.zeros((clen - zero_index, 2*self.chidden_size)), volatile=char_input.volatile, requires_grad=False).cuda()
Traceback (most recent call last):
  File "pytorch_ncrf.py", line 427, in <module>
    main()
  File "pytorch_ncrf.py", line 363, in main
    loss, predict = model(word_input, char_input, word_length_input, char_length_input, label_input)
  File "/home/john/anaconda3/envs/cross-lingual_NER/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "pytorch_ncrf.py", line 128, in forward
    predict = self.crf.decode(word_output, words.ne(Constants.PAD).float(), 1)
  File "/mnt/hdd/experiments/john/cross-lingual_NER/pytorch_crf.py", line 188, in decode
    pi[0] = energy[:, 0, -1, leading_symbolic:-1]
RuntimeError: The expanded size of the tensor (1) must match the existing size (9) at non-singleton dimension 2

 % sh ./run_lasagne_ncrf.sh
$ THEANO_FLAGS=device=cuda3 python lasagne_ncrf.py --train_data ./conll2002/esp.train_transferred_fasttext_idc_withoutDOCS --dev_data ./conll2002/esp.testa_withoutDOCS --test_data ./conll2002/esp.testb_withoutDOCS --word_vec_path ./glove-sbwc.i25_withou_head_d_s.vec --seed 10 --word_dropout 0.5 --use_crf --self_att --att_dropout 0.5 --log_interval 150 --log_path ./esp_sa_fasttext_idc_result
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/john/anaconda3/envs/cross-lingual_NER_theano/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/home/john/anaconda3/envs/cross-lingual_NER_theano/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/home/john/anaconda3/envs/cross-lingual_NER_theano/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 99, in init_dev
    **args)
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
GpuArrayException: cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
loading data...
building model...
training...
/home/john/anaconda3/envs/cross-lingual_NER_theano/lib/python2.7/site-packages/theano/tensor/subtensor.py:2197: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  rval = inputs[0].__getitem__(inputs[1:])
 150/1387 batches |  dev acc: 88.8984 | recall: 0.5902 | precision: 0.4812 | f1 0.5301 ********
 150/1387 batches | test acc: 88.9049 | recall: 0.5955 | precision: 0.5023 | f1 0.5449 ********
 300/1387 batches |  dev acc: 92.1167 | recall: 0.7138 | precision: 0.5922 | f1 0.6474 ********
 300/1387 batches | test acc: 91.7713 | recall: 0.7110 | precision: 0.6007 | f1 0.6512 ********
 450/1387 batches |  dev acc: 94.6050 | recall: 0.7359 | precision: 0.7189 | f1 0.7273 ********
 450/1387 batches | test acc: 93.9205 | recall: 0.7250 | precision: 0.7229 | f1 0.7239 ********
 600/1387 batches |  dev acc: 95.8277 | recall: 0.7943 | precision: 0.7725 | f1 0.7832 ********
 600/1387 batches | test acc: 95.4151 | recall: 0.7929 | precision: 0.7750 | f1 0.7838 ********

The vocabulary  size and dimension size already set to the both python files.
 % head -n 1 glove-sbwc.i25.vec
855380 300
parser.add_argument('--vocab_size', type=int, default=855380, help='vocab size')

john@serv-9200 ~/experiments/cross-lingual_NER
 % head conll2002/esp.train_transferred_fasttext_idc
UE B-ORG
rechaza O
Alemán B-MISC
llamar O
a O
boicot O
Británico B-MISC
cordero O
. O

john@serv-9200 ~/experiments/cross-lingual_NER

Thanks
John

**Comment by thespectrewithin** [comment]
please use pytorch 0.3.0 see if it fixes the issue

**Comment by thespectrewithin** [comment]
fixed. i think it works with 0.4.0 now.

**Comment by Jorigorn** [comment]
Thanks for your reply, switch to  0.3.0 can run it successfully. Thanks :)
