### ISSUE TITLE
Questions about the ablation test

### ISSUE THREAD

**Issue by ji-xin** [thespectrewithin/cross-lingual_NER#6]
In the paper, Table 2, the results of `Translation` do not match with any numbers from Table 1. So I'm wondering what kind of settings are the experiments in Table 2 run on?

Another relevant question would be, according to the ablation test (Table 2), using `Translation` provides about 4 percent improvement (for Spanish) over `Common Space`. However in Table 1 the improvement is about 6 percent, so where does the rest come from?

Thank you.

**Comment by thespectrewithin** [comment]
See the footnote on Page 7, results on Table 2 are obtained using glove for both translation and training the ner model, while for Table 1 we use fasttext for finding translations and glove for training ner model.
