### ISSUE TITLE
Two word vectors?

### ISSUE THREAD

**Issue by zyuuyuu** [thespectrewithin/cross-lingual_NER#8]
Thanks for the good work!

I noticed that you used two different Spanish word vectors in the training process:

1. The FastText vector trained on Wikipedia to feed into MUSE to generate mapping.

2. The GloVe vector to create word index before feeding into LSTMCRF.

Is there a reason to use two different vectors? What happened if we use the same vector both 1. and 2. ?

**Comment by thespectrewithin** [comment]
It's just that it's better to use fasttext to get word-to-word translations than glove and it's better but not much better to use glove for training ner models. Now I just use fasttext for both.

**Comment by zyuuyuu** [comment]
Thanks for the quick response!

Have you tested on other languages such as French?

**Comment by thespectrewithin** [comment]
I just used the conll datasets.

**Comment by mayhewsw** [comment]
Related question: for the common space experiments (Table 2), you used homemade glove embeddings. Did you try with fasttext also? I'm trying to reproduce that experiment with fasttext, and getting low scores. Wondering if it's the embeddings or a different bug.

**Comment by thespectrewithin** [comment]
Hey Stephen, I forgot if I have used fasttext for that, but the results shouldnt be much different from the glove results.
