### ISSUE TITLE
Confirm some additional experiment results on German

### ISSUE THREAD

**Issue by sbmaruf** [thespectrewithin/cross-lingual_NER#9]
For german, if we take unsupervised embeddings (BWET (adv.) + self-att without any dictionary) and also without any language-based based Capitalization feature, 
with five-run, I'm getting around, 41.77, 41.58, 41.81, 39.14, 43.67 = Average(41.59) +- std(1.44)
I am taking wiki-based fastext embedding (not cc+wiki) for word translation (word translation score 74.57@k=1) and german glove embeddings (given by you). I am only lacking the capitalization features that you extracted from wikipedia corpus. Is it safe to say without language-specific preprocessing (capitalization feature) this is the result? {Average(41.59) +- std(1.44)}

To me, it seems odd because capitalization feature should not give around ~16 F1 score increment.

for running the code what I did, I used MUSE ([by unsupervised.py](https://github.com/facebookresearch/MUSE/blob/master/unsupervised.py)) to translate `en`->`de` (used default hyperparameter given in muse directory, reproduced the given result 74.57@k=1 in the paper). Then used `run_load_muse.sh` (with default hyperparameter given in your repository) to generate a dictionary. Finally used `run_transfer_training_data.sh` (with default hyperparameter given in your repository) to create a new word to word translated NER dataset and finally used that dataset to train the model by `run_pytorch_ncrf.sh` (with default hyperparameter given in your repository).

Note I have to change some code to run. Like I had to read the dataset by 'latin-1' encoding and also exclude `-x-` from the dataset.

Can you confirm this result? or I am missing something from the paper? @thespectrewithin 

Note: I was able to reproduce the table 1 `BWET (id.c.) + self-att.` result with the same approach.

**Comment by thespectrewithin** [comment]
Did you lower case the character input?

**Comment by sbmaruf** [comment]
@thespectrewithin Thank you for the reply. In which run you did lower the character? Can you tell me the hyperparameter that needed to be tuned?

**Comment by thespectrewithin** [comment]
Cuz German has a different capitalization pattern than English, you should either lower case the char input for both languages which gives you roughly 50 f1 if I remember correctly, or you can use a German corpus say Wikipedia to count the number of times a word is capitalized and recapitalize the en-to-de word to word translated training data accordingly. Otherwise, as the model is trained with English capitalization pattern, it will overfit that pattern (all nouns in German are capitalized, so many words will be tagged as named entity), and lower the performance compared to say, without capitalization feature. Other hyper parameters are fine. Just try lower-case char input, and try the corpus based method.

**Comment by sbmaruf** [comment]
@thespectrewithin  I understand the reason for changing the capitalization feature. But at which step you change the capitalization? 
Did you change the capitalization after executing `transfer_training_data.py` (on the newly created word-to-word dataset)?

**Comment by thespectrewithin** [comment]
In utils, when you convert char to char index. Or when you translate. Either way. Should be pretty straightforward

**Comment by sbmaruf** [comment]
Hi @thespectrewithin  I just got the result.
For german, the result is,
47.23+47.52+49.40+46.58+47.78 = avg(47.708) +-std(.93)
Which is similar to table 2, row 2 within the standard deviation. 
Thank you for your response.
